font_family JetBrainsMono Nerd Font
font_size 10

shell_integration no-rc

background_opacity 0.85
confirm_os_window_close 0
cursor_trail 3
cursor_trail_decay 0.1 0.4
enable_audio_bell no
update_check_interval 0
map ctrl+shift+n launch --type=os-window --cwd=current
