preload = ~/.config/hypr/wallpapers/background.png
preload = ~/.config/hypr/wallpapers/background_right.png
preload = ~/.config/hypr/wallpapers/background_left.png

wallpaper = ,~/.config/hypr/wallpapers/background.png
wallpaper = HDMI-A-1,~/.config/hypr/wallpapers/background_right.png
wallpaper = DP-1,~/.config/hypr/wallpapers/background.png

splash = false
